version: "3.9"

services:
  devopsdb:
    image: kavya318506/db:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
      resources:
         limits:
            cpus: "2"
            memory: 125M
         reservations:
            cpus: "1"
            memory: 64M
    environment:
      user: kavya
      pass: cred@123
    networks:
      - mynetwork

  application:
    image: kavya318506/app:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
